# Generated by Django 4.2.4 on 2023-08-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblChild',
            fields=[
                ('ChildID', models.AutoField(primary_key=True, serialize=False)),
                ('Child_FirstName', models.CharField(max_length=200)),
                ('Child_SurName', models.CharField(max_length=200)),
                ('ChildPassword', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='tblEffort',
            fields=[
                ('EffortID', models.AutoField(primary_key=True, serialize=False)),
                ('Effort', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tblParent',
            fields=[
                ('ParentID', models.AutoField(primary_key=True, serialize=False)),
                ('Parent_FirstName', models.CharField(max_length=200)),
                ('Parent_SurName', models.CharField(max_length=200)),
                ('ParentEmail', models.EmailField(max_length=254, unique=True)),
                ('ParentPassword', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='tblPoints',
            fields=[
                ('PointsID', models.AutoField(primary_key=True, serialize=False)),
                ('Points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tblPriority',
            fields=[
                ('PriorityID', models.AutoField(primary_key=True, serialize=False)),
                ('Priority', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tblReminder',
            fields=[
                ('ReminderID', models.AutoField(primary_key=True, serialize=False)),
                ('Reminder', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='tblSubject',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserTaskHabit',
            fields=[
                ('UserTaskHabitID', models.AutoField(primary_key=True, serialize=False)),
                ('ObjectID', models.PositiveIntegerField()),
                ('ChildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblchild')),
                ('ContentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ParentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblparent')),
            ],
        ),
        migrations.CreateModel(
            name='tblTask',
            fields=[
                ('ActivityID', models.AutoField(primary_key=True, serialize=False)),
                ('Activity', models.TextField()),
                ('Description', models.TextField()),
                ('Completed', models.BooleanField(null=True)),
                ('DueDate', models.DateTimeField()),
                ('EffortID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tbleffort')),
                ('PointsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblpoints')),
                ('PriorityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblpriority')),
                ('ReminderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblreminder')),
            ],
            options={
                'ordering': ['-DueDate'],
            },
        ),
        migrations.CreateModel(
            name='tblQuestion',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblsubject')),
            ],
        ),
        migrations.CreateModel(
            name='tblHabit',
            fields=[
                ('ActivityID', models.AutoField(primary_key=True, serialize=False)),
                ('Activity', models.TextField()),
                ('Description', models.TextField()),
                ('Completed', models.BooleanField(null=True)),
                ('Frequency', models.DateTimeField()),
                ('EffortID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tbleffort')),
                ('PointsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblpoints')),
                ('PriorityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblpriority')),
                ('ReminderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblreminder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tblChoice',
            fields=[
                ('ChoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('ChoicesText', models.CharField(max_length=200)),
                ('IsCorrect', models.BooleanField()),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblquestion')),
            ],
        ),
        migrations.CreateModel(
            name='tblChildAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('CHildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblchild')),
                ('ChosenChoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblchoice')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblquestion')),
            ],
        ),
        migrations.AddField(
            model_name='tblchild',
            name='ParentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tblparent'),
        ),
    ]
