# Generated by Django 4.2.4 on 2023-09-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblhabit',
            name='Frequency',
        ),
        migrations.AddField(
            model_name='tblhabit',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
    ]
