# Generated by Django 4.2.4 on 2023-09-18 23:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_remove_tblhabit_frequency_tblhabit_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ActivityID', models.AutoField(primary_key=True, serialize=False)),
                ('Activity', models.TextField()),
                ('Description', models.TextField()),
                ('Completed', models.BooleanField(null=True)),
                ('Reminder', models.DateTimeField(null=True)),
                ('Effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('Priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('DueDate', models.DateTimeField()),
                ('Frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_point',
            fields=[
                ('Activity_pointID', models.AutoField(primary_key=True, serialize=False)),
                ('ActivityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('ChildID', models.AutoField(primary_key=True, serialize=False)),
                ('Child_FirstName', models.CharField(max_length=200)),
                ('Child_SurName', models.CharField(max_length=200)),
                ('Child_username', models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(limit_value=6)])),
                ('ChildPassword', models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(limit_value=16)])),
            ],
        ),
        migrations.CreateModel(
            name='ChildAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('attempt_answer', models.TextField()),
                ('isCorrect', models.BooleanField()),
                ('ChildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.child')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('ParentID', models.AutoField(primary_key=True, serialize=False)),
                ('Parent_FirstName', models.CharField(max_length=200)),
                ('Parent_SurName', models.CharField(max_length=200)),
                ('Parent_username', models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(limit_value=6)])),
                ('ParentEmail', models.EmailField(max_length=254, unique=True)),
                ('ParentPassword', models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(limit_value=16)])),
            ],
        ),
        migrations.CreateModel(
            name='Parent_Child',
            fields=[
                ('Parent_ChildID', models.AutoField(primary_key=True, serialize=False)),
                ('ChildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.child')),
                ('ParentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('PointID', models.AutoField(primary_key=True, serialize=False)),
                ('Point', models.IntegerField()),
                ('ChildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.child')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('correctanswer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_task',
            fields=[
                ('User_taskID', models.AutoField(primary_key=True, serialize=False)),
                ('ActivityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.activity')),
                ('ChildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.child')),
                ('ParentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.parent')),
            ],
        ),
        migrations.RemoveField(
            model_name='tblchildanswer',
            name='CHildID',
        ),
        migrations.RemoveField(
            model_name='tblchildanswer',
            name='ChosenChoice',
        ),
        migrations.RemoveField(
            model_name='tblchildanswer',
            name='QuestionID',
        ),
        migrations.RemoveField(
            model_name='tblchoice',
            name='QuestionID',
        ),
        migrations.RemoveField(
            model_name='tblhabit',
            name='EffortID',
        ),
        migrations.RemoveField(
            model_name='tblhabit',
            name='PointsID',
        ),
        migrations.RemoveField(
            model_name='tblhabit',
            name='PriorityID',
        ),
        migrations.RemoveField(
            model_name='tblhabit',
            name='ReminderID',
        ),
        migrations.RemoveField(
            model_name='tblquestion',
            name='SubjectID',
        ),
        migrations.RemoveField(
            model_name='tbltask',
            name='EffortID',
        ),
        migrations.RemoveField(
            model_name='tbltask',
            name='PointsID',
        ),
        migrations.RemoveField(
            model_name='tbltask',
            name='PriorityID',
        ),
        migrations.RemoveField(
            model_name='tbltask',
            name='ReminderID',
        ),
        migrations.RemoveField(
            model_name='usertaskhabit',
            name='ChildID',
        ),
        migrations.RemoveField(
            model_name='usertaskhabit',
            name='ContentType',
        ),
        migrations.RemoveField(
            model_name='usertaskhabit',
            name='ParentID',
        ),
        migrations.RenameModel(
            old_name='tblSubject',
            new_name='Subject',
        ),
        migrations.DeleteModel(
            name='tblChild',
        ),
        migrations.DeleteModel(
            name='tblChildAnswer',
        ),
        migrations.DeleteModel(
            name='tblChoice',
        ),
        migrations.DeleteModel(
            name='tblEffort',
        ),
        migrations.DeleteModel(
            name='tblHabit',
        ),
        migrations.DeleteModel(
            name='tblParent',
        ),
        migrations.DeleteModel(
            name='tblPoints',
        ),
        migrations.DeleteModel(
            name='tblPriority',
        ),
        migrations.DeleteModel(
            name='tblQuestion',
        ),
        migrations.DeleteModel(
            name='tblReminder',
        ),
        migrations.DeleteModel(
            name='tblTask',
        ),
        migrations.DeleteModel(
            name='UserTaskHabit',
        ),
        migrations.AddField(
            model_name='question',
            name='SubjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.subject'),
        ),
        migrations.AddField(
            model_name='childanswer',
            name='QuestionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.question'),
        ),
        migrations.AddField(
            model_name='activity_point',
            name='PointID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.points'),
        ),
    ]
