# Generated by Django 4.2.4 on 2023-09-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_activity_activity_point_child_childanswer_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='Point',
            new_name='TotalPoints',
        ),
    ]
