# Generated by Django 4.2.4 on 2023-10-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_rename_point_points_totalpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='ParentEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
