# Generated by Django 4.2.4 on 2023-10-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_parent_parentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(related_name='parents', through='APP.Parent_Child', to='APP.child'),
        ),
    ]
