# Generated by Django 4.2.4 on 2023-10-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_parent_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='Reminder',
        ),
        migrations.AddField(
            model_name='activity',
            name='DueTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='ReminderDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='ReminderTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='DueDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='Frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True),
        ),
    ]
