# Generated by Django 4.2.4 on 2023-10-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_remove_activity_reminder_activity_duetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
