# Generated by Django 4.2.4 on 2023-10-17 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_alter_activity_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user_task',
            field=models.ManyToManyField(related_name='activities', to='APP.user_task'),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='ActivityID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='APP.activity'),
        ),
    ]
