# Generated by Django 4.2.4 on 2023-10-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_activity_user_task_alter_user_task_activityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Activity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='task', max_length=10),
        ),
    ]
