# Generated by Django 4.2.4 on 2023-10-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_alter_activity_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user_task',
        ),
    ]
