# Generated by Django 4.2.4 on 2023-10-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_remove_activity_user_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Activity',
            field=models.CharField(choices=[('habit', 'Habit'), ('task', 'Task')], default='task', max_length=10),
        ),
    ]
