# Generated by Django 4.2.4 on 2023-10-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_alter_activity_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPoints',
            fields=[
                ('Activity_pointID', models.AutoField(primary_key=True, serialize=False)),
                ('Points', models.IntegerField()),
                ('ActivityID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.activity')),
            ],
        ),
        migrations.RemoveField(
            model_name='points',
            name='ChildID',
        ),
        migrations.AddField(
            model_name='child',
            name='TotalPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='child',
            name='activities',
            field=models.ManyToManyField(related_name='children', through='APP.User_task', to='APP.activity'),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='ActivityID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.activity'),
        ),
        migrations.DeleteModel(
            name='Activity_point',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
    ]
