# Generated by Django 4.2.4 on 2023-10-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_activitypoints_remove_points_childid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='CompletedDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='Activity',
            field=models.CharField(choices=[('task', 'Task'), ('habit', 'Habit')], default='task', max_length=10),
        ),
    ]
