# Generated by Django 4.2.4 on 2023-10-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_activity_completeddatetime_alter_activity_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Activity',
            field=models.CharField(choices=[('habit', 'Habit'), ('task', 'Task')], default='task', max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='CompletedDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
