# Generated by Django 4.2.4 on 2023-11-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_alter_activity_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='ProfileEmoji',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='Activity',
            field=models.CharField(choices=[('task', 'Task'), ('habit', 'Habit')], default='task', max_length=10),
        ),
    ]
