# Generated by Django 4.2.4 on 2023-11-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_child_profileemoji_alter_activity_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Activity',
            new_name='ActivityType',
        ),
    ]
