# Generated by Django 4.2.4 on 2023-11-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0017_rename_activity_activity_activitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ActivityPoints',
        ),
    ]
