# Generated by Django 4.2.4 on 2023-11-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_activity_points_delete_activitypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ActivityType',
            field=models.CharField(choices=[('habit', 'Habit'), ('task', 'Task')], default='task', max_length=10),
        ),
    ]
