# Generated by Django 4.2.4 on 2023-11-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0019_activity_image_alter_activity_activitytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='Image',
        ),
    ]
