# Generated by Django 4.2.4 on 2023-11-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0020_remove_activity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildFish',
            fields=[
                ('ChildFishID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=0)),
                ('ChildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.child')),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('FishID', models.AutoField(primary_key=True, serialize=False)),
                ('FishName', models.CharField(max_length=200)),
                ('FishPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FishImage', models.ImageField(upload_to='fish_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TankAdjustment',
            fields=[
                ('AdjustmentID', models.AutoField(primary_key=True, serialize=False)),
                ('TemperatureAdjustment', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('OxygenLevelAdjustment', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('WaterChange', models.BooleanField(default=False)),
                ('AdjustmentDateTime', models.DateTimeField(auto_now_add=True)),
                ('ChildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.child')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='SubjectID',
        ),
        migrations.AlterField(
            model_name='activity',
            name='ActivityType',
            field=models.CharField(choices=[('task', 'Task'), ('habit', 'Habit')], default='task', max_length=10),
        ),
        migrations.DeleteModel(
            name='ChildAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='childfish',
            name='FishID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.fish'),
        ),
        migrations.AddField(
            model_name='child',
            name='fishes',
            field=models.ManyToManyField(related_name='children_fishes', through='APP.ChildFish', to='APP.fish'),
        ),
    ]
