# Generated by Django 4.2.4 on 2023-11-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0021_childfish_fish_tankadjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='FishImage',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
