# Generated by Django 4.2.4 on 2023-11-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0022_alter_fish_fishimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='DailyRepeatCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='FrequencyTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='MonthlyRepeatDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='RepeatDay',
            field=models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, null=True),
        ),
    ]
