# Generated by Django 4.2.4 on 2023-11-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0023_activity_dailyrepeatcount_activity_frequencytime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ActivityType',
            field=models.CharField(choices=[('habit', 'Habit'), ('task', 'Task')], default='task', max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='DailyRepeatCount',
            field=models.IntegerField(),
        ),
    ]
