# Generated by Django 4.2.4 on 2023-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0024_alter_activity_activitytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='DailyRepeatCount',
            field=models.IntegerField(null=True),
        ),
    ]
