# Generated by Django 4.2.4 on 2023-11-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0025_alter_activity_dailyrepeatcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='MonthlyRepeatDay',
        ),
        migrations.AddField(
            model_name='activity',
            name='DailyRepeatHour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='EndTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='MonthlyRepeatDays',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='StartTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='WeeklyRepeatDays',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
