# Generated by Django 4.2.4 on 2023-11-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0026_remove_activity_monthlyrepeatday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='DailyRepeatCount',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='DailyRepeatHour',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='Frequency',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='FrequencyTime',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='MonthlyRepeatDays',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='RepeatDay',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='StartTime',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='WeeklyRepeatDays',
        ),
        migrations.AlterField(
            model_name='activity',
            name='ActivityType',
            field=models.CharField(choices=[('task', 'Task'), ('habit', 'Habit')], default='task', max_length=10),
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('HabitID', models.AutoField(primary_key=True, serialize=False)),
                ('Frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True)),
                ('RepeatDay', models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, null=True)),
                ('FrequencyTime', models.TimeField(blank=True, null=True)),
                ('MonthlyRepeatDays', models.CharField(blank=True, max_length=50, null=True)),
                ('DailyRepeatCount', models.IntegerField(null=True)),
                ('DailyRepeatHour', models.IntegerField(null=True)),
                ('StartTime', models.TimeField(null=True)),
                ('EndTime', models.TimeField(null=True)),
                ('WeeklyRepeatDays', models.CharField(max_length=50, null=True)),
                ('ActivityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.activity')),
            ],
        ),
    ]
