# Generated by Django 4.2.4 on 2023-11-15 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0027_remove_activity_dailyrepeatcount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='DailyRepeatHour',
        ),
    ]
