# Generated by Django 4.2.4 on 2023-11-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0028_remove_habit_dailyrepeathour'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task',
            name='HabitID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.habit'),
        ),
    ]
