# Generated by Django 4.2.4 on 2023-11-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0029_user_task_habitid'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='CompletedCount',
            field=models.IntegerField(null=True),
        ),
    ]
