# Generated by Django 4.2.4 on 2023-11-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0030_habit_completedcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='MonthlyRepeatDays',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='RepeatDay',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
