# Generated by Django 4.2.4 on 2023-11-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0031_alter_habit_monthlyrepeatdays_alter_habit_repeatday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='MonthlyRepeatDays',
            field=models.CharField(blank=True, max_length=3650, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='RepeatDay',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
