# Generated by Django 4.2.4 on 2023-12-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0032_alter_habit_monthlyrepeatdays_alter_habit_repeatday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='CompletedCount',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='FrequencyTime',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='MonthlyRepeatDays',
        ),
        migrations.AlterField(
            model_name='habit',
            name='DailyRepeatCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='Frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10, null=True),
        ),
    ]
