# Generated by Django 4.2.4 on 2023-12-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0033_remove_habit_completedcount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='user_task',
            name='ChildID',
        ),
        migrations.RemoveField(
            model_name='user_task',
            name='ParentID',
        ),
        migrations.AddField(
            model_name='user_task',
            name='ParentChildID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.parent_child'),
        ),
    ]
