# Generated by Django 4.2.4 on 2023-12-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0034_remove_child_activities_remove_user_task_childid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='DailyRepeatCount',
            field=models.IntegerField(null=True),
        ),
    ]
