# Generated by Django 4.2.4 on 2023-12-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0035_alter_habit_dailyrepeatcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='ResetCode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parent',
            name='ResetCode',
            field=models.IntegerField(default=0),
        ),
    ]
