# Generated by Django 4.2.4 on 2023-12-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0036_child_resetcode_parent_resetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ResetCode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='ResetCode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
