# Generated by Django 4.2.4 on 2023-12-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0037_alter_child_resetcode_alter_parent_resetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='Food',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='child',
            name='ChildPassword',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='childfish',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
