# Generated by Django 4.2.4 on 2023-12-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0038_fish_food_alter_child_childpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childfish',
            name='DateOfPurchase',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='childfish',
            name='FishFood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fish',
            name='Life',
            field=models.IntegerField(default=0),
        ),
    ]
