# Generated by Django 4.2.4 on 2023-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0039_childfish_dateofpurchase_childfish_fishfood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='ParentEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
