# Generated by Django 4.2.4 on 2023-12-29 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0040_alter_parent_parentemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Child_username',
            field=models.CharField(max_length=22, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=6)]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Parent_username',
            field=models.CharField(max_length=22, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=6)]),
        ),
    ]
