# Generated by Django 4.2.4 on 2024-01-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0041_alter_child_child_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='WeeklyRepeatDays',
        ),
    ]
