# Generated by Django 4.2.4 on 2024-01-10 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0042_remove_habit_weeklyrepeatdays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childfish',
            old_name='FishFood',
            new_name='FedLevel',
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='Food',
            new_name='FoodLevel',
        ),
        migrations.AlterField(
            model_name='child',
            name='ChildPassword',
            field=models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(limit_value=16)]),
        ),
        migrations.AlterField(
            model_name='child',
            name='Child_username',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
