# Generated by Django 4.2.4 on 2024-01-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0043_rename_fishfood_childfish_fedlevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childfish',
            name='FedTime',
            field=models.DateTimeField(null=True),
        ),
    ]
