# Generated by Django 4.2.4 on 2024-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0044_childfish_fedtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tankadjustment',
            name='AdjustmentDateTime',
        ),
        migrations.AddField(
            model_name='tankadjustment',
            name='OxygenAdjustmentTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tankadjustment',
            name='TemperatureAdjustmentTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tankadjustment',
            name='WaterChangeTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
