# Generated by Django 4.2.4 on 2024-01-21 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0045_remove_tankadjustment_adjustmentdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ChildPassword',
            field=models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(limit_value=6)]),
        ),
    ]
