# Generated by Django 4.2.4 on 2024-01-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0046_alter_child_childpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='childfish',
            name='RemainingLife',
            field=models.IntegerField(default=0),
        ),
    ]
