# Generated by Django 4.2.4 on 2024-02-04 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0047_childfish_remaininglife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ChildPassword',
            field=models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='ParentEmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='parent',
            name='ParentPassword',
            field=models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(limit_value=10)]),
        ),
    ]
