# Generated by Django 4.2.4 on 2024-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0048_alter_child_childpassword_alter_parent_parentemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childfish',
            name='Quantity',
        ),
        migrations.AlterField(
            model_name='parent',
            name='ParentEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
