# Generated by Django 4.2.4 on 2024-02-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0049_remove_childfish_quantity_alter_parent_parentemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='ParentEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
